_prefs: 
  mapid: curbyourlitter.84a5e3d7
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "Design by <a href='http://partnerandpartners.com'>Partner & Partners</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.9553
  - 40.7321
  - 17
description: A simple basemap that matches the identity of Curb Your Litter.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 14
name: Curb Your Litter
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - labels.mss
  - roads.mss
template: ''
